spring:
  datasource:
    url: jdbc:mysql://38.190.222.77:3306/mk_system?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: mk_system
    password: 8c5DS8GZzhWrPc5a
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 8
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 2
        max-active: 4
        min-idle: 1
        max-wait: -1ms
    redission:
      codec: org.redisson.codec.JsonJacksonCodec
      threads: 4
      netty:
        threads: 4
      single-server-config:
        address: "redis://${spring.redis.host}:${spring.redis.port}"
        database: ${spring.redis.database}
app:
  ip-xdb-path: /home/apps/ip2region.xdb
  upload-root: /home/apps/upload
